language: rust
sudo: false
matrix:
  include:
    - rust: stable
      env:
       - FEATURES=''
    - rust: stable
      env:
       - FEATURES='serialize'
    - rust: stable
      env:
       - FEATURES='integers'
    - rust: stable
      env:
       - FEATURES='serialize,integers'
    - rust: nightly
      env:
       - FEATURES=''
       - BENCH=0
script:
  - |
      cargo build --verbose --features "$FEATURES" &&
      cargo test --verbose --features "$FEATURES" &&
      ([ "$BENCH" != 1 ] || cargo bench --verbose --features "$FEATURES")
